### ISSUE TITLE
Problems compiling with latest DMD

### ISSUE THREAD

**Issue by Laeeth** [alphaKAI/twitter4d#11]
Hi.

Compiles fine with latest LDC (0.15.1 based on DMD v2.066.1 and LLVM 3.5.1)

But with DMD 2.067 I get:

twitter4d.d-mixin-33(33): Error: undefined identifier RangeError
twitter4d.d-mixin-34(34): Error: undefined identifier RangeError
twitter4d.d-mixin-37(37): Error: undefined identifier RangeError
twitter4d.d-mixin-40(40): Error: undefined identifier RangeError

**Comment by alphaKAI** [comment]
Thank you for reporting the problem. :-)
However, I’ve fixed the problem.
Please check my commit : https://github.com/alphaKAI/twitter4d/commit/8a37fb3aef4dd0e8aad9b2c41f5ed53feea7d947
