### ISSUE TITLE
use std.uri.encodeComponent instead of custom made urlEncode

### ISSUE THREAD

**Issue by WebFreak001** [alphaKAI/twitter4d#12]
Relying on phobos will help avoiding bugs

**Comment by WebFreak001** [comment]
I see from a previous commit that you have used encodeComponent before. Is there any reason to not use it?

**Comment by alphaKAI** [comment]
Sorry, I had some reason to not use, but I forgot details. Maybe encodeComponent has some problem (the function is not support the specification which required by twitter(this information may a lie...)).

**Comment by WebFreak001** [comment]
I checked the [phobos documentation](https://dlang.org/phobos/std_uri.html) and it says its according to 
RFC 3986, which is exactly [what twitter/oauth requires](https://dev.twitter.com/oauth/overview/percent-encoding-parameters) (at the top it says RFC 3986)

**Comment by alphaKAI** [comment]
Ok, I don't have any reason to use my implemented version.
If you submit the pull request which replace urlEncode with encodeComponent, I'll merge it.
